train:
  files: [yamls/pvc.yaml, yamls/workflow-train.yaml]
  parameters:
    model-name: mnist-torch
    pvc-name: mnist-torch
    pvc-size: 2Gi
    lakefs-secret-name: lakefs # temporary
    command: "python train.py --backend gloo --no_cuda --log_dir ./log --dataset_dir ~/dataset --save_path ~/saved_model/model_state_dict.pt"
    # command: "python train.py --aimd --api_key 915eb140-001d-4c55-985f-9b566b7e0752 --backend gloo --no_cuda --log_dir ./log --dataset_path ~/dataset --save_path ~/saved_model/model_state_dict.pt"
    working-dir: asset-hub-example
    image: tsz.io/t9k/pytorch-1.12.1:sdk-0.4.0-t9kuser
    request-cpu: 4000m
    request-memory: 2Gi
    limit-cpu: 8000m
    limit-memory: 4Gi
    worker-num: "3"
evaluate:
  files: [yamls/pvc.yaml, yamls/workflow-evaluate.yaml]
  parameters:
    model-name: mnist-torch
    pvc-name: mnist-torch
    pvc-size: 2Gi
    lakefs-secret-name: lakefs # temporary
    command: "python evaluate.py --no_cuda --dataset_dir ~/dataset --load_path ~/saved_model/model_state_dict.pt --output_dir ~/metrics"
    working-dir: asset-hub-example
    image: tsz.io/t9k/pytorch-1.12.1:sdk-0.4.0-t9kuser
    request-cpu: 2000m
    request-memory: 2Gi
    limit-cpu: 4000m
    limit-memory: 4Gi
    worker-num: "3"
