apiVersion: batch.tensorstack.dev/v1beta1
kind: WorkflowTemplate
metadata:
  name: apply-k8s-yaml
spec:
  params:
    - name: subpath
      description: PVC subpath in which the git repository is cloned.
    - name: namespace
      description: Namespace in which the resources are created.
      default: demo
    - name: pvc_name
      description: PVC name.
  workspaces:
    - name: pvc
  results: []
  type: SeqPod
  seqPod:
    steps:
      - image: "tsz.io/t9k/kubectl:10.20"
        name: kubectl-apply
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
        script: |
          #!/bin/bash
          set -xe
          cd $(workspaces.pvc.path)
          cd $(params.subpath)

          while read -r line; do
              sed 's/${pvc-name}/$(params.pvc_name)/' ${line:2} | kubectl apply -n $(params.namespace) -f -
          done < <(yq r config.yaml train.files)
