apiVersion: batch.tensorstack.dev/v1beta1
kind: WorkflowTemplate
metadata:
  name: asset-hub-retrain
  labels: {}
spec:
  params:
    - name: git_repo_url
    - name: dataset_reference
    - name: new_branch_name
    - name: pvc_name
    - name: model_id
  workspaces:
    - name: pvc
    - name: lakefs-secret
    - name: lakectl-secret
  results: []
  type: DAG
  dag:
    failureStrategy: StopAllWorkflowTemplates
    templates:
      - name: git-clone
        workflowTemplateRef: git-clone
        params:
          - name: url
            value: $(params.git_repo_url)
        workspaces:
          - name: pvc
            workspace: pvc
        retries: 3
        when: []
        dependencies: []
      - name: download-dataset
        workflowTemplateRef: download-dataset
        params:
          - name: reference
            value: $(params.dataset_reference)
        workspaces:
          - name: pvc
            workspace: pvc
          - name: lakefs-secret
            workspace: lakefs-secret
        retries: 3
        when: []
        dependencies: []
      - name: apply-k8s-yaml
        workflowTemplateRef: apply-k8s-yaml
        params:
          - name: subpath
            value: $(tasks.git-clone.results.repo-name)
          - name: pvc_name
            value: $(params.pvc_name)
        workspaces:
          - name: pvc
            workspace: pvc
        retries: 0
        when: []
        dependencies:
          - git-clone
          - download-dataset
      - name: upload-model
        workflowTemplateRef: upload-model
        params:
          - name: new_branch_name
            value: $(params.new_branch_name)
          - name: model_id
            value: $(params.model_id)
        workspaces:
          - name: pvc
            workspace: pvc
          - name: lakefs-secret
            workspace: lakefs-secret
          - name: lakectl-secret
            workspace: lakectl-secret
        retries: 0
        when: []
        dependencies:
          - apply-k8s-yaml

---
apiVersion: batch.tensorstack.dev/v1beta1
kind: WorkflowRun
metadata:
  name: retrain-hash-code
  labels:
    batch.tensorstack.dev/workflowTemplate: asset-hub-train-pytorch
spec:
  params:
    - name: git_repo_url
      value: https://github.com/t9k/asset-hub-example
    - name: dataset_reference
      value: mnist/main/
    - name: new_branch_name
      value: new-branch
    - name: pvc_name
      value: retrain-pvc
  serviceAccountName: managed-project-sa
  timeout: 1h0m0s
  workflowTemplateRef: train-pytorch
  workspaces:
    - name: pvc
      persistentVolumeClaim:
        claimName: retrain-pvc
    - name: lakefs-secret # temporary
      secret:
        secretName: lakefs
    - name: lakectl-secret # temporary
      secret:
        secretName: lakectl
