apiVersion: batch.tensorstack.dev/v1beta1
kind: WorkflowTemplate
metadata:
  name: upload-model
spec:
  params:
    - name: new_branch_name
      default: "new_branch"
    - name: subpath
      default: "saved_model/"
    - name: model_id
  workspaces:
    - name: pvc
    - name: lakefs-secret # temporary
    - name: lakectl-secret # temporary
  results: []
  type: SeqPod
  seqPod:
    steps:
      - image: "tsz.io/t9k/build-sdk:1.60.0-t9kuser"
        name: get-dataset
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
        script: |
          #!/bin/bash
          set -xe
          cd $(workspaces.pvc.path)

          # unimplemented
          # assethub upload $(params.model_id) $(params.subpath)

          # temporary
          S3CFG_PATH="$(workspaces.lakefs-secret.path)/.s3cfg"
          if [[ -f "$S3CFG_PATH" ]]; then
              cp $S3CFG_PATH ~
          else
              echo "Failed to upload model: file .s3cfg not found"
              exit 1
          fi

          LAKETCL_PATH="$(workspaces.lakectl-secret.path)/.lakectl.yaml"
          if [[ -f "$LAKETCL_PATH" ]]; then
              cp $LAKETCL_PATH ~
          else
              echo "Failed to upload model: file .lakectl.yaml not found"
              exit 1
          fi

          echo "Uploading model to s3://$$(params.model_id) ..."
          lakectl branch create lakefs://$(params.model_id)/$(params.new_branch_name) --source lakefs://mnist-torch/main
          s3cmd put -r $(params.subpath) s3://$(params.model_id)/$(params.new_branch_name)/
          echo "Done."
