apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $(model-name)
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: $(pvc-size)
  storageClassName: tsz-cephfs
